# Generated by Django 3.0.5 on 2021-01-31 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_przychodu_rozchodu', models.DateTimeField(default=django.utils.timezone.now)),
                ('tytul_rozchodu_przychodu', models.CharField(max_length=200)),
                ('kwota_rozchodu_przychodu', models.IntegerField()),
                ('status_rozchodu_przychodu', models.CharField(choices=[('ok', 'Zaksięgowany'), ('czeka', 'Niezaksięgowany')], default='czeka', max_length=5)),
                ('forma_platnosci', models.CharField(choices=[('kasa', 'do/z kasy'), ('konto', 'wpłata/wypłata z konta'), ('inne', 'inne')], default='kasa', max_length=10)),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_przychodu_rozchodu'],
            },
        ),
    ]
