# Generated by Django 3.0.5 on 2021-01-31 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odbiorca', models.CharField(max_length=200)),
                ('nr_katalogowy', models.CharField(max_length=200)),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('forma_platnosci_zam', models.CharField(choices=[('przelew', 'przelew'), ('pobranie', 'płatne przy odbiorze'), ('opłacone', 'opłacone')], default='przelew', max_length=10)),
                ('kwota_plat_przy_odbiorze', models.IntegerField()),
                ('dostawca', models.CharField(choices=[('IC', 'InterCars'), ('GR', 'Gordon'), ('AL', 'AutoLand'), ('APP', 'AutoPartner Płock'), ('APG', 'Auto-Partner Gdańsk'), ('AUTKO', 'Autko'), ('XPartner', 'XPartner'), ('Allegro', 'Allegro'), ('CerMotor', 'Cermotor'), ('Inne', 'Inne')], max_length=10)),
                ('data_zamowienia', models.DateTimeField(default=django.utils.timezone.now)),
                ('termin_dostawy', models.CharField(choices=[('następna trasa', 'następna trasa'), ('dzisiaj po poludniu', 'dzisiaj po poludniu'), ('jutro rano', 'jutro rano'), ('jutro po południu', 'jutro po południu'), ('kilka dni', 'kilka dni')], max_length=30)),
                ('wybor_statusu_zam', models.CharField(choices=[('czeka', 'czekamy na dostawę'), ('dostarczony', 'dostarczony'), ('niedostarczony', 'niedostarczony-korekta'), ('użyty', 'użyty'), ('magazyn', 'magazyn'), ('zwrot', 'zwrot')], default='czeka', max_length=30)),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
