# Generated by Django 3.0.5 on 2021-01-31 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0002_zamowienia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zamowienia',
            options={'ordering': ['-data_zamowienia']},
        ),
        migrations.RenameField(
            model_name='zamowienia',
            old_name='pracownik',
            new_name='pracownik_zam',
        ),
    ]
