# Generated by Django 3.0.5 on 2021-01-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0003_auto_20210131_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienia',
            name='kwota_plat_przy_odbiorze',
            field=models.IntegerField(default=0),
        ),
    ]
