# Generated by Django 3.0.5 on 2021-02-07 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strona', '0010_auto_20210207_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kosztorysy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zgloszenia', models.DateTimeField(default=django.utils.timezone.now)),
                ('nazwa_klienta', models.CharField(max_length=200)),
                ('tel_klienta', models.CharField(blank=True, max_length=20)),
                ('mail_klienta', models.EmailField(blank=True, max_length=200)),
                ('nr_vin', models.CharField(max_length=17)),
                ('marka_model', models.CharField(blank=True, max_length=200)),
                ('opis_kosztorysu', models.TextField()),
                ('status_kosztorysu', models.CharField(choices=[('czeka', 'czeka'), ('wprowadzony', 'wprowadzony do Integry'), ('w trakcie', 'w trakcie wyceny'), ('czeka na sprawdzenie', 'wyceniony - do sprawdzenia'), ('sprawdzony: OK', 'sprawdzony: OK'), ('sprawdzony: POPRAWIONY', 'sprawdzony, poprawiony'), ('wysłany', 'wysłany klientowi'), ('zatwierdzony, umówiony', 'zatwierdzony, umówiony'), ('niezaakceptowany', 'niezaakceptowany przez klienta')], default='czeka', max_length=30)),
                ('powod_odrzucenia', models.TextField(blank=True)),
                ('pracownik_zam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_zgloszenia'],
            },
        ),
    ]
