# Generated by Django 3.0.5 on 2021-02-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0011_kosztorysy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kosztorysy',
            old_name='pracownik_zam',
            new_name='pracownik',
        ),
    ]
