# Generated by Django 3.0.5 on 2021-02-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0012_auto_20210207_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obroty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_od', models.DateField()),
                ('data_do', models.DateField()),
                ('nazwisko_mech', models.CharField(max_length=100)),
                ('imie_mech', models.CharField(max_length=100)),
                ('obrot_towary', models.IntegerField()),
                ('obrot_uslugi', models.IntegerField()),
            ],
            options={
                'ordering': ['-data_od'],
            },
        ),
    ]
